### ISSUE TITLE
Section 3.4 Discover Response subject_syntax_types_discriminations

### ISSUE THREAD

**Issue by andreasabr** [EWC-consortium/eudi-wallet-rfcs#15]
The discover response mentions the field   "subject_syntax_types_discriminations": [
    "did:key:jwk_jcs-pub",
    "did:ebsi:v1"
  ],

The meaning of this field name is not clear and requires revision, also because discrimination might be seen inappropriate.

**Comment by andreasabr** [comment]
@lalc @georgepadayatti we need to identify first what this parameter `subject_syntax_types_discriminations` actually means. 

My understanding is that the syntax types listed cannot be used and will be rejected. @georgepadayatti what is your opinion on this?

**Comment by georgepadayatti** [comment]
> @lalc @georgepadayatti we need to identify first what this parameter `subject_syntax_types_discriminations` actually means.
> 
> My understanding is that the syntax types listed cannot be used and will be rejected. @georgepadayatti what is your opinion on this?

My understanding is that discrimination in this context means 'variations' in a DID method for a subject supported by the issuer wallet. For e.g. `did:ebsi` has v1, v2 e.t.c, and `did:key` can have different multi-codec support.

**Comment by andreasabr** [comment]
@georgepadayatti in the example, it states the following: 

```
  "subject_syntax_types_supported": [
    "did:key",
    "did:ebsi"
  ],
  "subject_syntax_types_discriminations": [
    "did:key:jwk_jcs-pub",
    "did:ebsi:v1"
  ],
```

It specifies the supported syntax types and the discriminations paramter can then either state what are the accepted variations of the previous defined syntax types or the not accepted variations.

If it just details the supported variations of the previous mentioned syntax types, these two parameters could be merged to something like this: 
```
  "subject_syntax_types_supported": [
    "did:key:jwk_jcs-pub",
    "did:ebsi:v1",
    "did:ebsi:v2"
  ],
```

**Comment by georgepadayatti** [comment]
> @georgepadayatti in the example, it states the following:
> 
> ```
>   "subject_syntax_types_supported": [
>     "did:key",
>     "did:ebsi"
>   ],
>   "subject_syntax_types_discriminations": [
>     "did:key:jwk_jcs-pub",
>     "did:ebsi:v1"
>   ],
> ```
> 
> It specifies the supported syntax types and the discriminations paramter can then either state what are the accepted variations of the previous defined syntax types or the not accepted variations.
> 
> If it just details the supported variations of the previous mentioned syntax types, these two parameters could be merged to something like this:
> 
> ```
>   "subject_syntax_types_supported": [
>     "did:key:jwk_jcs-pub",
>     "did:ebsi:v1",
>     "did:ebsi:v2"
>   ],
> ```

This makes sense.
