### ISSUE TITLE
Section 3.1 Usage of the scope parameter 

### ISSUE THREAD

**Issue by andreasabr** [EWC-consortium/eudi-wallet-rfcs#20]
When utilizing a scope parameter for requesting VC(s), the scope value must fulfill specific requirements such as: 

- scope value MUST be an alias for a well-defined Presentation Definition that will be referred to in the presentation_submission
- scope value MUST allow the Verifier to determine the identifiers of the Presentation Definition and Input Descriptor(s) in the presentation_submission response parameter (definition_id and descriptor_map.id respectively) 
- It is RECOMMENDED to use collision-resistant scope values.

An example (ac. to the specification) is: scope=com.example.healthCardCredential_presentation

**Comment by lalc** [comment]
This makes sense. Can you please raise it as a PR?

**Comment by georgepadayatti** [comment]
> When utilizing a scope parameter for requesting VC(s), the scope value must fulfill specific requirements such as:
> 
> * scope value MUST be an alias for a well-defined Presentation Definition that will be referred to in the presentation_submission
> * scope value MUST allow the Verifier to determine the identifiers of the Presentation Definition and Input Descriptor(s) in the presentation_submission response parameter (definition_id and descriptor_map.id respectively)
> * It is RECOMMENDED to use collision-resistant scope values.
> 
> An example (ac. to the specification) is: scope=com.example.healthCardCredential_presentation

@lalc @andreasabr Question, is the use case for scope similar to `presentation_defintion_uri`? When a verifier uses the `scope` field, then the holder wallet should already be aware, of how to resolve the corresponding presentation definition.

**Comment by andreasabr** [comment]
@georgepadayatti the standard specifies that scope values should map to a presentation definition but it is out of scope how this mapping is achieved. 

The example scope mentioned (com.example.healthCardCredential_presentation) is indeed an URI, but does not necessarily have to be one. It also mentions the option of having a separate specification defining those scope values. This is something that could be interesting for us!? 

When using a URI for the scope pointing to the presentation definition, the benefit is not clear, since it will work similar to the presentation_definition_uri.
