### ISSUE TITLE
Section 3.1 Response_mode

### ISSUE THREAD

**Issue by andreasabr** [EWC-consortium/eudi-wallet-rfcs#21]
The response mode is defined in the RFC-002 as required value that must be set to direct_post, whereas the OIDC4VP standard defines it as optional. 

Question: Is EWC requiring that the mode is set to direct_post?

**Comment by georgepadayatti** [comment]
There are 2 ways the response to a verifier wallet can be sent from a holder wallet:

1) Direct post to the `response_uri` where `vp_token` and `presentation_submission` are encoded in the body using the `application/x-www-form-urlencoded` content type.
2) Redirection to a `redirect_uri` with `vp_token` and `presentation_submission` as query parameters

The direct post approach is prescribed to address the following use cases:

It has been defined to address the following use cases:

1. The Verifier and Wallet are located on different devices, thus, the Wallet cannot send the Authorization Response to the Verifier using a redirect.
2. The Authorization Response size exceeds the URL length limits of user agents, so flows relying only on redirects (such as Response Mode fragment) cannot be used. In those cases, the Response Mode direct_post is the way to convey the Verifiable Presentations to the Verifier without the need for the Wallet to have a backend.

**Comment by georgepadayatti** [comment]
@andreasabr @lalc We can keep both if agreed by the WP 3.1.1 and raise a PR if necessary

**Comment by lalc** [comment]
Yes, ok with a PR. @andreasabr Can you?
