### ISSUE TITLE
Discovery of OAuth Authorization server should use RFC8414 and /.well-known/oauth-authorization-server

### ISSUE THREAD

**Issue by ntsbs** [EWC-consortium/eudi-wallet-rfcs#23]
Currently, the [Section 3.0](https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#30messages) describes that the OAuth Authorization Server Metadata is fetched via `/.well-known/openid-configuration`, but OID4VCI Draft 12 Section 10.2.3 says that the authorization server should be fetched as defined in [RFC8414](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-12.html#RFC8414).

This means the OAuth 2.0 Authorization Server metadata is obtained from the oauth-authorization-server well-known location which should be `/.well-known/oauth-authorization-server`

**Comment by georgepadayatti** [comment]
I think both are acceptable as specified in the last para of [section 3](https://www.rfc-editor.org/rfc/rfc8414.html#section-3) in RFC 8414.


> Some OAuth applications will choose to use the well-known URI suffix "openid-configuration".  As described in [Section 5](https://www.rfc-editor.org/rfc/rfc8414.html#section-5), despite the identifier "/.well-known/openid-configuration", appearing to be OpenID specific, its usage in this specification is actually referring to a general OAuth 2.0 feature that is not specific to OpenID Connect.

**Comment by ntsbs** [comment]
This is more a legacy support as stated in section 5. 
`Going forward, OAuth authorization server metadata locations should use the transformation defined in this specification.`

I think we should only allow one option if there is no reason to support multiple ones. Having multiple options just increases implementation efforts and reduces the likeliness of interoperability.

**Comment by georgepadayatti** [comment]
> This is more a legacy support as stated in section 5. `Going forward, OAuth authorization server metadata locations should use the transformation defined in this specification.`
> 
> I think we should only allow one option if there is no reason to support multiple ones. Having multiple options just increases implementation efforts and reduces the likeliness of interoperability.

Yes makes sense to avoid ambiguity. @lalc
