### ISSUE TITLE
Public key resolution for `kid` specified in a JWT

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/eudi-wallet-rfcs#34]
There are multiple ways for resolving the public keys using the `kid`:

1. Resolve the JWKs endpoint in the AS configuration and match the public key using the key identifier.
2. If the key identifier is a DID then use a DID resolver to obtain the public key

**Comment by lalc** [comment]
Yes, we should add this to the RFC in my min. Also adding @endimion to this discussion

**Comment by endimion** [comment]
Yes agreed.. I think the most straightforward way is how @georgepadayatti described above... should we add this? or do you have somehting else in mind?

**Comment by lalc** [comment]
@andreasabr, Pls comment as needed, and @georgepadayatti can raise a PR to update this to the existing RFC. Let's formally make a release soon (v1.0) as most comments are in.

**Comment by georgepadayatti** [comment]
One comment from Mert Aybat (Signicat): 

If for whatever reason a system defines both: a jwks endpoint and a did.key, in that case probably we need to define a default choice and in my opinion it should be in that case the jwks endpoint since we are using an extension over oidc specs. Alternatively you could resolve both and even do some validations.

**Comment by endimion** [comment]
In the case of a did:key one could argue that why make another call to the jwks endpoing since you have all the info you need already ... But I hear Mert's reasoning as well. In my opinion we should just define an "EWC" approach to this that ensures a "happy" path.. and close the issue. At the end of the day if someone wants to resolve all ways and validate with all keys its up to them...

**Comment by ntsbs** [comment]
I also think the kid is either a did or an identifier which must be found in the JWKS. If you have a did I would not expect the wallet to lookup the JWKS and just resolve the did

**Comment by merayb** [comment]
Small clarification: my comment previously posted was about systems that define a jwks uri in their well-known endpoint and additionally define a did:key.  

@endimion I completely agree with you. This is really very quickly solvable. As you say, we need an "EWC" happy flow spec. In my opinion the wallet should first look for a jwks uri in the well-known endpoint and try to resolve that and if it is not there figure it out from the did:key 
My reasoning is simply based on the fact that we are dealing with oidc specs here.

**Comment by lalc** [comment]
@merayb Can you pls review the changes and approve it?
