### ISSUE TITLE
RFC-001 Issuer Metdata discovery response

### ISSUE THREAD

**Issue by endimion** [EWC-consortium/eudi-wallet-rfcs#44]
In the [discovery response of the issuer]( https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#34-discover-response ) in [v12](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-12.html#section-10.2.3) of OIDC  the logo of the issuer is under the key  url

In [version 13](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#section-10.2.3), the same is under the key uri.

Some wallet providers have already adopted v13. The current ARF defines v12.  What is our official approach in this?

Do we move to v13 or ask wallet providers to revert to v12 (which might be problematic...)

**Comment by endimion** [comment]
As discussed in slack we agreed to exclude the logo. as it is optional . If nobody objects I will close this in 1 hour...

**Comment by georgepadayatti** [comment]
> As discussed in slack we agreed to exclude the logo. as it is optional . If nobody objects I will close this in 1 hour...

And `cover` field can be excluded as well.
