### ISSUE TITLE
Usage of PKCE 

### ISSUE THREAD

**Issue by andreasabr** [EWC-consortium/eudi-wallet-rfcs#46]
In the RFC001, specifically in section 3.5, authorization request, it is defined that we are using PKCE. The example, including the description, defines it in a way that makes it seem that PKCE is mandatory. Nevertheless, the use of PKCE is optional according to the OIDC standard. 

On the other hand, EBSI WCT requires the usage of PKCE, but our EWC ITB issuer implementation does not use it. 

Now, what would we like to define in the RFC, namely making the usage of PKCE optional or mandatory? 
@lalc @endimion @ntsbs

**Comment by peppelinux** [comment]
PKCE is optional is OIDC Core 1.0 but required in OIDC iGov and OIDC FAPI and in OAuth 2.0 Security Best Current Practice.

we can say that PKCE is not present in OIDC Core 1.0 because Core was released before the born of PKCE and it keeps it's original requirement asset for interop retrocompatibility.

At the same time, for the purpose of the issuance, using the auth code flow, PKCE is mandatory according to OpenID4VCI.

https://github.com/openid/OpenID4VCI/blob/main/openid-4-verifiable-credential-issuance-1_0.md#authorization-endpoint-authorization-endpoint

**Comment by andreasabr** [comment]
The RFC001 is based on the draft 12 of OIDC4CI (https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-12.html) and it only RECOMMENDS to use PKCE. The same is true for the latest version of OIDC4CI (https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html) which is the first approved implementers draft. 

Since I believe its a good security feature, I was raising the question if we should make it mandatory or optional within the EWC scope.

**Comment by peppelinux** [comment]
oh yes @andreasabr, I made confusion between openid4vci and the italian profile that made PKCE mandatory to prevent replay attacks

https://github.com/openid/OpenID4VCI/blob/main/openid-4-verifiable-credential-issuance-1_0.md#replay-prevention

I agree with you

**Comment by lalc** [comment]
In my mind we should stick to the spec unless there is any strong need from the LSP perspective. 

We could consider the security aspects in future scope.

**Comment by endimion** [comment]
My two cents.  Maybe we should keep it optional as draft 12 of [OIDC4CI] (https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-12.html)  only RECOMMENDS to use PKCE? I agree, of course, that it is a pretty important security feature but as @lalc  suggests lets stick to the specs for now (just in case any wallet hasn't implemented it yet) and security is not really our focus at the moment....  I will add support for it in the EWC RFC Issuer service @andreasabr within the next few days hopefully and let everyone know :)

**Comment by endimion** [comment]
Hey all PKCE is supported by the auth code flow and the tests are added in the ITB.
