### ISSUE TITLE
Additional “EAA Provider”-LPID required (EWC RFC 005)

### ISSUE THREAD

**Issue by wfolkendt** [EWC-consortium/eudi-wallet-rfcs#57]
The defined LPID is usable only for legal persons who want to use the EUDIW in the Holder and Relying Party role.
Legal persons who want to use the wallet in the EAA Provider role need a LPID which includes as an additional attribute the public key or a key identifier (e.g. DID). usually this key is related to specific component of the trust infrastructure (e.g. public key of a qualified seal, key generated by the EUDIW, key related to a VDR,...). They also need a mechanism to enable unknown relying parties to access this key.
The resulting LPID variants are called “EAA Provider”-LPIDs. Each EAA provider shall include the concrete “EAA Provider”-LPID instances in the header of the issued  EAAs. The SD-JWT-VC specification allows that. By doing this, the so called “Identity attestation chaining” mechanism is implemented. This step enables each relying party EUDIW to get access to all the public keys required to verify the whole identity attestation issuer chain simply by accessing the data in the EAA header.
The following variants of the “issuer” LPIDs should be supported:
A)	A public key generated by the LPID holder EUDIW shall be included as an additional attribute named for example “EUDIW issuer public key”
B)	The public key of the holder legal entity qualified seal should be included as an additional attribute named for example “QSEAL public key”
For A) the “authentic source” from LPID provider perspective may be the Wallet Instance Attestation issued by the  Qualified  Wallet Provider. The WIA is accessed by the PID Provider during LPID issuance.
For B) the “authentic source” from LPID provider perspective may be the “QSEAL Infrastructure Attestation” issued by the  qualified seal service provider. The “QSEAL Infrastructure Attestation” shall be accessed by the PID Provider during LPID issuance. This additional step needs to be added to the interaction diagram.
The presentation accessible through the following link explains the issue in more detail: https://nextcloud.idunion.org/s/enZDRWaTMtXttWM

**Comment by malinnorlander** [comment]
As discussed earlier we don't see the need to develp a separate trust model for EAAs, the SSI-model used for QEAAs will scale for EAAs as well.
The LPID will work for legal persons regardless of whet role they will take on: holder, issuer and/or relying party. We do not support EAA-LPID or Issuer-LPID.
