### ISSUE TITLE
LPID header shall include PID Provider public keys (EWC RFC 005)

### ISSUE THREAD

**Issue by wfolkendt** [EWC-consortium/eudi-wallet-rfcs#58]
Assumption: There will be MS in which the LPID Provider sign the QEAAs with their existing qualified seal pivate key and which include the CA x509 certificate chain in the header.
 
The LPID is sealed by the PID Provider (step nr. 25) in the interaction diagram. The Relying Party wallet needs the PID Provider x.509 seal certificate chain to get access to the public keys needed to verify data integrity, authenticity and identity of the LPID. The German PID provider has proposed to include the corresponding x.509 seal certificate chain in the SD-JWT-VC header. This is possible according to the SD-JWT-VC specification. 
The presentation accessible through the following link explains the issue in more detail: https://nextcloud.idunion.org/s/enZDRWaTMtXttWM

**Comment by malinnorlander** [comment]
Work related to keys/certificates will be added in later revisions of the RFC. There is ongoing work around this subject and we expect standards to be developed or at least propsed during fall.
