### ISSUE TITLE
Invalid examples of authorization_details parameter

### ISSUE THREAD

**Issue by pa-rw** [EWC-consortium/eudi-wallet-rfcs#64]
The provided examples depict the authorization_details parameter as an object. However, RFC 9396 (OAuth 2.0 Rich Authorization Request) states in section 2 that authorization_details should be a JSON array of objects.

The example request shown above adheres to the RFC and correctly employs an array of objects.

**Comment by georgepadayatti** [comment]
This is being addressed as part of #63

**Comment by lalc** [comment]
@georgepadayatti Could we close this as fixed after draft-13 PR merge?

**Comment by lalc** [comment]
Completed as per PR #63

**Comment by georgepadayatti** [comment]
> @georgepadayatti Could we close this as fixed after draft-13 PR merge?

Yes. Updated to an array.
