### ISSUE TITLE
Authorisation Server metadata response_types_supported vp_token and vp_formats_supported

### ISSUE THREAD

**Issue by pa-rw** [EWC-consortium/eudi-wallet-rfcs#65]
What does response_types_supported vp_token and vp_formats_supported mean in the context of the Authorisation Server? 

Shouldn't response_types_supported include code?

https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/bc05e6323dc86f3fdfaaa7869dd0d4dc025940ff/ewc-rfc001-issue-verifiable-credential.md?plain=1#L326-L328

https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/bc05e6323dc86f3fdfaaa7869dd0d4dc025940ff/ewc-rfc001-issue-verifiable-credential.md?plain=1#L355-L366

**Comment by lalc** [comment]
@georgepadayatti Could we close this after draft 13 merge?

**Comment by georgepadayatti** [comment]
> @georgepadayatti Could we close this after draft 13 merge?

Yes have updated the metadata accordingly.

**Comment by lalc** [comment]
Completed as per PR #63
