### ISSUE TITLE
Credential Offer credentials field is not matching the OID4VCI Draft 12

### ISSUE THREAD

**Issue by ntsbs** [EWC-consortium/eudi-wallet-rfcs#7]
The credential offer response in [rfc001](https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#32credential-offer-response) is not compatible with the referenced version of the OID4VCI spec.

The `credentials` field should be an 
> An array of unique strings that each identify one of the keys in the name/value pairs stored in the credentials_supported Credential Issuer metadata property.
[OID4VCI Draft 12 Section 4.1.1](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-4.1.1)

The non-normative example from the spec is as follows:
```
{
   "credential_issuer": "https://credential-issuer.example.com",
   "credentials": [
      "UniversityDegreeCredential",
      "org.iso.18013.5.1.mDL"
   ],
   "grants": {
      "authorization_code": {
         "issuer_state": "eyJhbGciOiJSU0Et...FYUaBy"
      },
      "urn:ietf:params:oauth:grant-type:pre-authorized_code": {
         "pre-authorized_code": "adhjhdjajkdkhjhdj",
         "user_pin_required": true
      }
   }
}
```

**Comment by lalc** [comment]
This change is accepted. The earlier version was coming from EBSI conformant wallet implementation specs.
