### ISSUE TITLE
Include format for sd-jwt+vc

### ISSUE THREAD

**Issue by ntsbs** [EWC-consortium/eudi-wallet-rfcs#8]
The current editor's draft of the OID4VCI spec already defines the format for SD-JWT VC [here](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#appendix-A.3.1).

We should include the format `vc+sd-jwt` in the Credential Issuer Metadata object [RFC001 3.4](https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#34-discover-response)

**Comment by georgepadayatti** [comment]
This make sense. Would you be interested in raising a PR against the same ?

**Comment by ntsbs** [comment]
Can do, I think we should adopt the proposed [credential format profile](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-ietf-sd-jwt-vc) for SD-JWT. As far as I know the OpenID Credential Working Group is very to close to publishing this as an implementers draft version 1.

**Comment by lalc** [comment]
jwt and sd-jwt is supported in the RFC001. The supported formats are provided here: https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-supported-formats.csv
