### ISSUE TITLE
Credential Issuer Metadata credentials_supported field must be an object

### ISSUE THREAD

**Issue by ntsbs** [EWC-consortium/eudi-wallet-rfcs#9]
The credential issuer metadata field `credentials_supported` received in [RFC001 3.4 Discover response](https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#34-discover-response) must not be an array, but an object according to [OID4VCI draft 12 Section 10.2.3](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-10.2.3)

Current:
```
"credentials_supported": [
    {
      "format": "jwt_vc",
      "types": [
        "VerifiableCredential",
        "VerifiableAttestation",
        "VerifiablePortableDocumentA1"
      ],
      "trust_framework": {
        "name": "ebsi",
        "type": "Accreditation",
        "uri": "TIR link towards accreditation"
      },
      "display": [
        {
          "name": "Portable Document A1",
          "locale": "en-GB"
        }
      ]
    }
  ]
```

Expected:
```
"credentials_supported": {
        "VerifiablePortableDocumentA1": {
            "format": "vc+sd-jwt",
           ...
        },
       "VerifiablePortableDocumentA2": {
            "format": "vc+sd-jwt",
           ...
        }
}
```

**Comment by lalc** [comment]
This change is accepted. The supported credential formats are documented here: https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-supported-formats.csv
