### ISSUE TITLE
RFC-003 - Align vct with ARF and PID rulebook by defining type as "urn:eu.europa.ec.eudi:pid:1"

### ISSUE THREAD

**Issue by jtalir** [EWC-consortium/eudi-wallet-rfcs#90]
One of the most important interoperability goal is to agree on credential type for PID. Current ARF (PID Rulebook) is talking only about MDOC PID version but it has valuable suggestions for Attestation type to be "eu.europa.ec.eudi.pid.1" https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/latest/annexes/annex-3/annex-3.01-pid-rulebook/#22-attestation-type-and-namespace

There is also pull request to include SD-JWT-VC format into PID rulebook https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/160 that specifically suggest a value for vct in SD-JWT-VC to be "urn:eu.europa.ec.eudi:pid:1". Let's follow this approach in RFC-003.

**Comment by lalc** [comment]
@LeoneRiello74 Could you please check this?

**Comment by LeoneRiello74** [comment]
done

**Comment by jtalir** [comment]
I rebased pull request so it's possible to merge it.
