### ISSUE TITLE
RFC-003 - Allow credential offer by value

### ISSUE THREAD

**Issue by jtalir** [EWC-consortium/eudi-wallet-rfcs#92]
Current version limits in section 3.1 to provide credential offer by reference. I don't see a big issue if we provide also possibility to provide credential offer by value as per chapter 4.2.1 in OID4VCI - https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-sending-credential-offer-by

Primary reasoning is that it is the value used by referential issuer implemented by NiScy that already provide testing PID from multiple countries (Portugal, Estonia, Czechia, Netherlands, Luxembourgh). Here is the link https://issuer.eudiw.dev/. Issuer itself needs to be aligned with latest ARF with regards to Attestation type and claims in PID to be interoperable.

**Comment by lalc** [comment]
@LeoneRiello74 Could you please check this?

**Comment by LeoneRiello74** [comment]
accepted, I'll add this comment in the next version release

**Comment by LeoneRiello74** [comment]
closed

**Comment by jtalir** [comment]
Thanks. This will probably require some feedback whether all wallet providers are ok with accepting credential offer by value but this may happen when ITB will include RFC003.
