### ISSUE TITLE
RFC-003 - Process diagram improvements

### ISSUE THREAD

**Issue by jtalir** [EWC-consortium/eudi-wallet-rfcs#93]
These are just small suggestion for improvements of process diagram:
 - Include credential offer process as the first step for the case of authorization code flow (similar to what is in RFC-001)
 - Switch columns "Government Identity Provider"  and "Authentic Source". Authentic source is behind IdP with no direct communication to other entities. This could improve readability of process
 - "Data Acquisition from Authentic Source" is essential part of PID creation and I'd expect this part to reside in between of Credential Request and Credential Response, not earlier. 
 - "Verify Wallet's Certificate of Conformity" is also something that could fit more after Credential Request or maybe Token Request (Authorization Request is not part of pre-authotized code flow)

**Comment by lalc** [comment]
@LeoneRiello74 Could you please check this?

**Comment by LeoneRiello74** [comment]
done during the editing session with the working group
