### ISSUE TITLE
RFC-003 - Is reference to EBSI required?

### ISSUE THREAD

**Issue by jtalir** [EWC-consortium/eudi-wallet-rfcs#94]
I'd say it is already 100% guaranteed that EBSI will play no role for PID issuance where trust model will be based on trust lists (ARF, draft implementing acts). I don't see any advantage to include EBSI in this RFC.

**Comment by georgepadayatti** [comment]
> I'd say it is already 100% guaranteed that EBSI will play no role for PID issuance where trust model will be based on trust lists (ARF, draft implementing acts). I don't see any advantage to include EBSI in this RFC.

Agree to this

**Comment by lalc** [comment]
@LeoneRiello74 Can you pls check this?

**Comment by jtalir** [comment]
Agree, now there is no reference to EBSI.
